name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: chciken/tlmboyci:latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
        submodules: 'recursive'
    - name: configure
      run: |
           chmod a+x source_me.bash
           ./source_me.bash
           mkdir build
           cd build
           cmake tlmboy ..
    - name: build tlmboy
      working-directory: ./build
      run: cmake --build . --target tlmboy --config Release
    - name: build tests
      working-directory: ./build
      run: cmake --build . --target test_cpu
    - name: run tests
      working-directory: ./build/tests
      run: |
            export TLMBOY_ROOT=${GITHUB_WORKSPACE}
            ./test_cpu
