name: Build and Test CI

env:
  TLMBOY_ROOT: ${GITHUB_WORKSPACE}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: chciken/tlmboyci:latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
           chmod a+x source_me.bash
           ./source_me.bash
           mkdir build
           cd build
           cmake tlmboy ..
    - name: build tlmboy
      working-directory: ./build
      run: cmake --build . --target tlmboy --config Release
    - name: build tests
      working-directory: ./build
      run: cmake --build . --target test_blarrg_cpuinstr01
    - name: run tests
      working-directory: ./build/tests
      run: ./test_blarrg_cpuinstr01
    - name: coverage report
      run: ./coverage_report.bash
    - name: archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage/coverage.html
