name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: chciken/tlmboyci:latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
        submodules: 'recursive'
    - name: configure
      run: |
           chmod a+x source_me.bash
           ./source_me.bash
           mkdir build
           cd build
           cmake tlmboy ..
    - name: build tlmboy
      working-directory: ./build
      run: |
           cmake --build . --target tlmboy --config Release -j$(nproc)
           cmake --build . --target tlmboy_test -j$(nproc)
           cmake --build . --target tlmboy_static_test -j$(nproc)
    - name: build tests
      working-directory: ./build
      run: cmake --build . --target tests -j$(nproc)
    - name: run tests
      working-directory: ./build/tests
      run: |
            export TLMBOY_ROOT=${GITHUB_WORKSPACE}
            ./test_bus
            ./test_cpu
            ./test_gdb
            ./test_memory
            ./test_ppu --headless
            ./test_symfile_tracer
            ./test_blarrg_cpuinstr01 --headless
            ./test_blarrg_cpuinstr02 --headless
            ./test_blarrg_cpuinstr03 --headless
            ./test_blarrg_cpuinstr04 --headless
            ./test_blarrg_cpuinstr05 --headless
            ./test_blarrg_cpuinstr06 --headless
            ./test_blarrg_cpuinstr07 --headless
            ./test_blarrg_cpuinstr08 --headless
            ./test_blarrg_cpuinstr09 --headless
            ./test_blarrg_cpuinstr10 --headless
            ./test_blarrg_cpuinstr11 --headless
    - name: coverage report
      run: |
           export CODACY_PROJECT_TOKEN=${{secrets.CODACY_TOKEN}}
           ./coverage_report.bash
